### ISSUE TITLE
Need to change the color of Cards.

### ISSUE THREAD

**Issue by ssat4805** [sabesansathananthan/github-readme-medium-card#2]
Need to change the Cards colors and make it like Github README stats [cards](https://github.com/anuraghazra/github-readme-stats).

**Comment by shrinish123** [comment]
I can solve the issue. Could you please assign to me

**Comment by fletcherrippon** [comment]
Can I be assigned this issue?

**Comment by SriCoD** [comment]
i would love working on this

**Comment by ssat4805** [comment]
According to the FCFS(First come First serve)  @shrinish123 , I will assign @shrinish123 . Could you please mention how long you will take for this?

**Comment by shrinish123** [comment]
Sorry, for late reply but you can assign it to others

**Comment by fletcherrippon** [comment]
I will like to be assigned

**Comment by ssat4805** [comment]
I will assign @fletcherrippon

**Comment by fletcherrippon** [comment]
@sabesansathananthan can you describe the issue in a bit more detail?

**Comment by IsuruAriyarathne** [comment]
I love to work on this. Can you assign me .

**Comment by ssat4805** [comment]
Need to add the parameter named "theme" and we need to implement themes like Github README stats...
Cards could be like Pinned repositories. Now I aligned like vertical and horizontal... We need to eliminate that option and we need to add a parameter called "post_count'... In medium, we could get maximum of10 posts ..
align the cards like pinned repositories and the width and height of card like same as GitHub pinned repository...

![Capture](https://user-images.githubusercontent.com/36799589/95682993-2aa92f80-0c06-11eb-825a-6297371c7d7b.JPG)


It has a great opportunity to reach many people. You will have a great opportunity to be a part of this project.  So, now I suggest all of you do this work and we will see. @fletcherrippon , @IsuruAriyarathne , @SriCoD 
Refer this repo
https://github.com/anuraghazra/github-readme-stats

**Comment by IsuruAriyarathne** [comment]
Thank you for your opportunity.
